name: Mi primera automatizacion
on:
  push:
    branches:
      [ '*' ]
jobs:
  linter:
    name: Checking angular styles
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install deps
        run: npm ci
      - name: Run Linter
        run: npm run lint
  lhci:
    name: Lighthouse LHCI
    runs-on: ubuntu-latest
    steps:
      - name: Git clone
        uses: actions/checkout@v3
      - name: Setup NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: Install deps
        run: npm ci
      - name: Build
        run: npm run build
      - name: Run Lighthouse
        run: npm run lhci autorun
